### ISSUE TITLE
Generate Google Play Signing Key.

### ISSUE THREAD

**Issue by zanzendegi** [tcfev/fordem-app#2]
In order to sign our android artifacts, we need to generate a signing key and store it secure.

**Comment by armantorkzaban** [comment]
Should we use Fastlane Match for it? @zanzendegi

**Comment by zanzendegi** [comment]
We don't need Fastlane.

**Comment by zanzendegi** [comment]
FYI, I have generated the signing keys. We need a vault to keep it secure and accessible to everyone in the team. Should we keep it in 1password for organizations?

**Comment by armantorkzaban** [comment]
What about keeping them in Github secrets or a private Repo?

**Comment by zanzendegi** [comment]
GH Secrets are not a good idea (We already have them for CI/CD). The problem with secrets is that once we loose them, there is no way to have them again. Secrets will never be visible.

A private repo is a better idea. We should discuss if new members join the organization whether they should have access to the signing keys (they will see the private repos).

**Comment by zanzendegi** [comment]
@armantorkzaban

**Comment by armantorkzaban** [comment]
Secrets are now stored in tcfev/secrets. Access to this repo is limited and a select number of members who need those secrets will be added to the repo. upon request/need.
